apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
# Existen varios tipos que podemos configurar.
# Opaque: cifra las variables que pongamos, sin más (es el más genérico)
type: Opaque
data:
    # Ojo porque los valores en este archivo deben estar codificados en base64.
    # En mac y linux lo podemos hacer con el comando $ echo mi-password | base64
    VAR_NAME: value # codificado en base64
    VAR_NAME_2: value # codificado en base64
